### ISSUE TITLE
QRCode and QRCodeBuilder: Both have a ``data`` property. Possibilities to reduce data copying around 

### ISSUE THREAD

**Issue by heuer** [mnooner256/pyqrcode#23]
QRCode and QRCodeBuilder have a ``data`` property. It's unclear why both instances should have this property. 
Maybe QRCode could utilize the QRCodeBuilder.data property?

**Comment by mnooner256** [comment]
I does not make a copy, it is just identical references. Both are used within their respective objects. But QRCode.data and QRCodeBuilder.data are the same object.
