### ISSUE TITLE
"shiftjis" printed to terminal when creating qr-codes (windows-only)

### ISSUE THREAD

**Issue by blueForestIcarus** [mnooner256/pyqrcode#43]
I noticed that when calling pyqrcode.create() the string "shiftjis" is printed to the terminal.
I know that shiftjis is an encoding (not sure it is the right one for what I am doing) but even so, I don't think the create method should be printing out anything as it takes away control from the user of the library, if they want to know the encoding they can put a print statement into their code.

The message is definitely coming from line 158, which is the only print statement in the entire file. It appears to be a debug line left their by mistake.

Strangely, this problem only occurs when running on windows.

**Comment by mnooner256** [comment]
Well that's embarrassing :/. I fix it obviously. I also altered my distribution script so print statements cannot leak into the module again.

Thanks for the report.
