### ISSUE TITLE
How to reduce the padding on generated images ?

### ISSUE THREAD

**Issue by sbpro86** [mnooner256/pyqrcode#54]
Hello,

Is is possible to reduce/remove the padding on generated images ?

Thanks.

**Comment by mnooner256** [comment]
I am assuming you are referring to the "quiet zone" that surrounds the the QR Code. According to the standard that zone is supposed to 4 modules in size. I often find that size to be excessive, especially at larger scales. 

The renderers have a parameter called "quiet_zone" that that lets you set that value.

    four_module_border = qrcode.create('Some value").png('Some file', scale=5)
    no_border = qrcode.create('Some value").png('Some file', scale=5, quiet_zone=0)

I hope the that helps.

[Documentation for png (all renderers have the same parameter)](https://pythonhosted.org/PyQRCode/moddoc.html#pyqrcode.QRCode.png)

**Comment by mfrasca** [comment]
who can close this solved issue?

**Comment by leandroxbr** [comment]
Still works like a charm! Thanks @mnooner256 :)
