### ISSUE TITLE
which license statement is correct?

### ISSUE THREAD

**Issue by mfrasca** [mnooner256/pyqrcode#56]
the License file states "all rights reserved", but the project is registered as BSD:
![image](https://user-images.githubusercontent.com/122869/28529133-5a6bba9e-7055-11e7-8940-aa6a46c1b38d.png)
which is the case?

**Comment by mfrasca** [comment]
cc-ing @heuer and all other contributors:
@marcobiscaro2112 @svanheulen @luzfcb @menglewis @broamski @zhicheng 
cheers, Mario

**Comment by svanheulen** [comment]
The "all rights reserved" is in reference to the copyright, not the license.

**Comment by mfrasca** [comment]
I'm not sure I follow this. the License file in the root directory does not make any explicit reference to BSD. it does state this "https://en.wikipedia.org/wiki/All_rights_reserved".

**Comment by mfrasca** [comment]
I'm sorry, the text **is** the BSD-3
https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22BSD_License_2.0.22.2C_.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29

**Comment by heuer** [comment]
Hi Mario,

It's the 3-Clause BSD License, correct.

It's a permissive license so you can use the project in allmost all cases regardless which license your code uses.

Regards,
Lars

**Comment by mfrasca** [comment]
[from wikipedia](https://upload.wikimedia.org/wikipedia/commons/1/1d/Floss-license-slide-image.png)
![image](https://user-images.githubusercontent.com/122869/28624477-d8e3fcc6-71de-11e7-835a-06f25e86aa43.png)
