### ISSUE TITLE
only produce the path element, not the whole file

### ISSUE THREAD

**Issue by mfrasca** [mnooner256/pyqrcode#57]
I would like to embed the QR svg element produced by this library in my own svg producing software, and the only way I see to do that, is to write the file into a `StringIO`, then extracting the element I need.

according to the docstring for `QRCode.svg`, 
>If only the code itself is desired, set the *xmldecl* to false. This will result in a fragment that contains only the "drawn" portion of the code.

however, if I do that, I only get rid of the leading `<?xml version="1.0" encoding="UTF-8"?>`, not also the root `svg` element. I would like the naked `path` element, and I would like it returned in a string, not written to a file.

**Comment by heuer** [comment]
Omitting the SVG element isn't possible.
It's possible to omit additionally the namespace delaration; this is useful if you want to embed the generated QR Code in HTML files. 

Anyway, extracting the path should be trivial.

BTW, you don't have to write to a file:

```python
>>> import io
>>> import pyqrcode
>>> qr = pyqrcode.create('Test')
>>> out = io.BytesIO()
>>> qr.svg(out, scale=10, xmldecl=False, svgns=False)
>>> out.getvalue()
```

**Comment by mfrasca** [comment]
I have this, for the time being:
```python
class add_qr_functor:
    import pyqrcode
    def __init__(self):
        import StringIO
        import re
        self.buffer = StringIO.StringIO()
        self.pattern = re.compile('<svg.*>(<path.*>)</svg>')

    def __call__(self, x, y, text, scale=1):
        qr = self.pyqrcode.create(text)
        self.buffer.truncate(0)
        qr.svg(self.buffer, xmldecl=False, quiet_zone=0, scale=scale)
        match = self.pattern.match(self.buffer.getvalue())
        result_list = [match.group(1)]
        if x != 0 or y != 0:
            result_list.insert(0, '<g transform="translate(%s,%s)">' % (x, y))
            result_list.append('</g>')
        return '\n'.join(result_list)

add_qr = add_qr_functor()
```

**Comment by heuer** [comment]
Should work, maybe you'll have to use BytesIO if you'll switch to Py3. I think the svg method expects to write binary data (I'm not sure, though, I'll have to look into the code).

Small suggestion for the regex pattern:

```python
self.pattern = re.compile('(<path[^>]+>)')
```

**Comment by mfrasca** [comment]
I have switched to `io`,
(as a note to myself: since I'm reusing the buffer, I need not only truncate(0), I also have to seek(0).)
the expression you suggest works, if I replace `match` by `search`.
I agree it is possibly better, but looks uglier, replacing the `.` by `[^>]`.
if you have an example where StringIO does not work, I'm interested.

**Comment by heuer** [comment]
In Py3 it won't work:
```python
>>> import io
>>> import pyqrcode
>>> qr = pyqrcode.create('Text')
>>> out = io.StringIO()
>>> qr.svg(out)
Traceback (most recent call last):
[...]
    write_bytes(b'<?xml version="1.0" encoding="UTF-8"?>\n')
TypeError: string argument expected, got 'bytes'
>>> out = io.BytesIO()
>>> qr.svg(out)
>>> out.getvalue()
b'<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" height="29" width="29" class="pyqrcode"><path stroke="#000" class="pyqrline" d="M4 4.5h7m1 0h2m1 0h2m1 0h7m-21 1h1m5 0h1m3 0h1m3 0h1m5 0h1m-21 1h1m1 0h3m1 0h1m1 0h2m1 0h1m2 0h1m1 0h3m1 0h1m-21 1h1m1 0h3m1 0h1m2 0h4m1 0h1m1 0h3m1 0h1m-21 1h1m1 0h3m1 0h1m1 0h1m3 0h1m1 0h1m1 0h3m1 0h1m-21 1h1m5 0h1m3 0h1m3 0h1m5 0h1m-21 1h7m1 0h1m1 0h1m1 0h1m1 0h7m-13 1h2m-5 1h2m2 0h2m1 0h1m1 0h1m1 0h1m1 0h1m1 0h1m-20 1h2m1 0h2m2 0h2m1 0h1m1 0h1m2 0h3m-19 1h2m1 0h1m2 0h1m2 0h2m3 0h1m1 0h4m-20 1h6m1 0h1m3 0h1m1 0h1m2 0h3m-18 1h2m1 0h1m1 0h2m4 0h1m7 0h1m-13 1h3m1 0h4m3 0h1m-20 1h7m2 0h4m1 0h2m2 0h2m-20 1h1m5 0h1m1 0h2m1 0h8m1 0h1m-21 1h1m1 0h3m1 0h1m3 0h2m1 0h1m1 0h1m1 0h1m1 0h1m-20 1h1m1 0h3m1 0h1m2 0h2m1 0h2m3 0h2m-19 1h1m1 0h3m1 0h1m3 0h1m1 0h1m4 0h4m-21 1h1m5 0h1m2 0h1m1 0h2m3 0h1m1 0h1m-19 1h7m5 0h1m1 0h1m1 0h1m1 0h2"/></svg>\n'
```

**Comment by heuer** [comment]
> I agree it is possibly better, but looks uglier, replacing the . by [^>]

I find it more clear / explicit, but if your pattern works, feel free to use it :)

**Comment by heuer** [comment]
If you use BytesIO, you'll have to decode the value into the used encoding (default: UTF-8) before passing it into re.search / re.match

```python
    def __call__(self, x, y, text, scale=1, encoding='utf-8'):
        qr = self.pyqrcode.create(text)
        self.buffer.truncate(0)
        self.buffer.seek(0)
        qr.svg(self.buffer, xmldecl=False, quiet_zone=0, scale=scale, encoding=encoding)
        match = self.pattern.search(self.buffer.getvalue().decode(encoding))
        result_list = [match.group(1)]
        if x != 0 or y != 0:
            result_list.insert(0, '<g transform="translate(%s,%s)">' % (x, y))
            result_list.append('</g>')
        return '\n'.join(result_list)
```

**Comment by mfrasca** [comment]
sorry I was so brief in reacting, I wasn't yet busy with Python3, and I am now: I moved the program from which I'm using pyqrcode to python3, and I've decided I would leave py2 behind.
I changed the pattern again, because I need to have the original size in pixels, so I can resize it to fit a given square:
`'svg': re.compile('<svg.*height="([0-9]*)".*>(<path.*>)</svg>')`
I'm happy with the current solution.
